4750 privacy policy
medic/cht-core pull request #6692
Opened 2020-10-26 10:40 UTC by latin-panda

# Description

Migration of privacy policy components and enabling mobile navigation to messages tab.
The privacy policy component and directive are merged into one component.

medic/cht-core#4750

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2020-10-26 10:41 UTC, latin-panda commented
Hi @dianabarsan, Could you please take a look at this PR? Thank you!!

2020-10-27 08:03 UTC, dianabarsan requested changes
Great work!! Just a couple of minor comments inline.

2020-10-29 04:05 UTC, latin-panda commented on webapp/src/ts/services/privacy-policies.service.ts
> +        const settings = {
Fixed

2020-10-29 04:25 UTC, latin-panda commented on webapp/src/ts/app.component.ts
> +  private checkPrivacyPolicy() {
Done

2020-10-29 04:28 UTC, latin-panda commented on webapp/tests/karma/ts/modules/privacy-policies/privacy-policy.component.spec.ts
> +    expect(privacyPoliciesService.accept.args[0][0]).to.deep.equal(policy);
I've made a copy to avoid this problem.
`component.privacyPolicy = { ...policy };`

2020-10-29 04:32 UTC, latin-panda commented on webapp/tests/karma/ts/modules/privacy-policies/privacy-policy.component.spec.ts
> +   component.privacyPolicy = policy;
Fixed

2020-10-29 05:12 UTC, latin-panda commented on webapp/src/ts/services/privacy-policies.service.ts
> +          html: this.sanitizer.bypassSecurityTrustHtml(decodedContent),
Replaced it with sanitize in html context, unit test updated too.

2020-10-29 07:24 UTC, dianabarsan approved these changes
Cool! 👍🏻

2020-10-29 07:24 UTC, merged