doc: CONTRIBUTING.md: is->if, remove dupe section (Improving our Doc...)
medic/cht-core pull request #6747
Opened 2020-11-21 05:19 UTC by andy5995

# Description

Fixes some grammar (is->if), removes a duplicate section; also adds a link to the cht-docs repo.

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2020-11-22 19:30 UTC, garethbowen requested changes
Thanks! There's one small fix we should make at the same time (suggestion inline).

You can ignore the build failure - it looks like a temporary issue...

2020-11-22 19:30 UTC, garethbowen commented on CONTRIBUTING.md
> +**Note:** [medic-docs](https://github.com/medic/cht-docs) does not involve release management and acceptance testing. Help us maintain the quality of our documentation by submitting a pull request (P
We renamed this repo from medic-docs -> cht-docs so we should fix this at the same time.
```suggestion
**Note:** [cht-docs](https://github.com/medic/cht-docs) does not involve release management and acceptance testing. Help us maintain the quality of our documentation by submitting a pull request (PR) with any suggested changes.
```

2020-11-24 03:01 UTC, garethbowen approved these changes

2020-11-24 03:02 UTC, merged

2020-11-24 07:22 UTC, andy5995 commented
@garethbowen Glad I could help a little! :)