refactored navigation tests
medic/cht-core pull request #6842
Opened 2021-01-14 04:22 UTC by ngaruko

# Description

[description]

medic/cht-core#[number]

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-01-20 15:29 UTC, newtewt requested changes
Some small changes but otherwise looking good. I think you need to rebase as it seems like the diff is picking up changes that already exist. Might be github not refreshing when changes are pushed.

2021-01-20 15:29 UTC, newtewt commented on tests/page-objects/common/common.po.js
> +    utils.deprecated('common.po.goToPeople', 'commmon.po.goToPeopleNative');
These two methods look the same aside from the deprecated method. Do we need both?

2021-01-20 15:29 UTC, newtewt commented on tests/page-objects/common/common.po.js
> +    return await element(by.css(locator)).isPresent();
I would chose to either remove this `isAtNative` method and await it elsewhere or remove the return here.

2021-02-17 11:48 UTC, dianabarsan commented
Closing in favor of https://github.com/medic/cht-core/pull/6934

2021-02-17 11:48 UTC, closed without merging