refactored api/server.js tests
medic/cht-core pull request #6843
Opened 2021-01-14 04:22 UTC by ngaruko

# Description

[description]

medic/cht-core#[number]

# Code review items

- Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- Tested: Unit and/or e2e where appropriate
- Internationalised: All user facing text
- Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-01-19 19:51 UTC, newtewt requested changes
Nice work on moving to the disabled flow. A few questions

2021-01-19 19:51 UTC, newtewt commented on .github/workflows/build.yml
> +        name: Results Logs ${{ matrix.node-version }}
This seems to be a duplicate job `tests-e2e-disabled`. If it is necessary can you update the name and it's key?

2021-01-19 19:51 UTC, newtewt commented on tests/conf.js
> +      'e2e/login/login.specs.js',
These have been moved to the conf-disabled already. Can you remove from here?

```
      'e2e/create-meta-db.js',
      'e2e/login/login.specs.js'
```

2021-01-19 19:51 UTC, newtewt commented on tests/utils.js
> -    dest: `tests/results/`,
Is this intentional? It will break the artifact path when run on github.  If it is, then the build.yml needs updated as well.

2021-02-12 19:41 UTC, dianabarsan commented
I've already enabled these tests, without needed changes.

2021-02-15 06:10 UTC, closed without merging