contact summary e2e tests angular 10
medic/cht-core pull request #6890
Opened 2021-01-28 18:14 UTC by newtewt

# Description

update contract summary tests to async/await and work with angular10 changes. 

https://github.com/medic/angular10-migration/issues/80

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-01-31 23:18 UTC, craig-landry requested changes

2021-01-31 23:18 UTC, craig-landry commented on tests/e2e/contact-summary.js
> +    expect(await contactsPo.cardFieldText('alicetag')).toBe(ALICE.name + ' ' + ALICE.phone);
I know it's preexisting stuff, but please update the syntax on this and the others below while you're running thought this bit of code.
```suggestion
    expect(await contactsPo.cardFieldText('alicetag')).toBe(`${ALICE.name} ${ALICE.phone}`);
```

2021-01-31 23:18 UTC, craig-landry commented on tests/helper.js
> +      const msg = `Element taking too long to appear in the DOM ${element.locator()}`;
Thanks for using the template string here :)

2021-01-31 23:18 UTC, craig-landry commented on tests/page-objects/contacts/contacts.po.js
>      searchBox.sendKeys(query);
Both [clear](https://www.protractortest.org/#/api?view=webdriver.WebElement.prototype.clear) and [sendKeys](https://www.protractortest.org/#/api?view=webdriver.WebElement.prototype.sendKeys) look to return promises and you'll need to `await` them to be sure those keystrokes happen before the `click` on the following line. With that though, I would have expected this test to fail most or all of the time, so perhaps I'm missing something here. Is there something else involved that's causing these actions to happen in the desired sequence?
```suggestion
    await searchBox.clear();
    await searchBox.sendKeys(query);
```

2021-01-31 23:18 UTC, craig-landry commented on tests/utils.js
> -
I kind of like this better with the newline separating the other lines. Just my personal preference though.

2021-02-02 21:12 UTC, newtewt commented on tests/e2e/contact-summary.js
> +
Are you referring to the blank line?

2021-02-03 13:50 UTC, newtewt commented
@craig-landry  can you re-review. I believe I have addressed everything

2021-02-04 16:33 UTC, craig-landry reviewed
Just a nitpick thing and otherwise all set here.

2021-02-04 16:33 UTC, craig-landry commented on tests/e2e/contact-summary.js
> +
Yeah, I thought there were 2 blank lines there.

2021-02-04 16:33 UTC, craig-landry commented on tests/utils.js
> +
```suggestion

```

There are whitespaces here that should be removed. Chances are your editor slipped them in there to "help".

2021-02-05 22:51 UTC, craig-landry approved these changes

2021-02-08 14:51 UTC, merged