68 purge angular 10
medic/cht-core pull request #6905
Opened 2021-02-05 13:54 UTC by newtewt

# Description

async/await and angular 10 updates for purge test

https://github.com/medic/angular10-migration/issues/68

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-02-05 23:05 UTC, craig-landry requested changes

2021-02-05 23:05 UTC, craig-landry commented on tests/page-objects/reports/reports.po.js
> +  reportsByUUID: uuid => module.exports.list().all(by.css('li[data-record-id="' + uuid + '"]')),
Some template string goodness to tidy that up and make sure we don't end up in quoting trouble, and then extracting to a variable to be sure we're conveying that they're the same thing:

```suggestion
  const reportUUIDSelector = `li[data-record-id="${uuid}"]`;
  reportByUUID: uuid => module.exports.list().all(by.css(reportUUIDSelector)).first(),
  reportsByUUID: uuid => module.exports.list().all(by.css(reportUUIDSelector)),
```

2021-02-08 15:06 UTC, newtewt commented on tests/page-objects/common/common.po.js
>      helper.waitUntilReady(hamburgerMenuOptions);
I added the return here. However, I was a bit reluctant as I didn't use this code. I'll ensure the tests pass before merging.

2021-02-09 21:32 UTC, craig-landry requested changes

2021-02-09 21:32 UTC, craig-landry commented on tests/page-objects/reports/reports.po.js
> +  reportsByUUID: uuid => module.exports.list().all(by.css(`li[data-record-id="${uuid}"]`)),
I see you got the string template stuff, but perhaps forgot about the request to extract to a variable. I was going to suggest this...
```
  const matchedListItems = by.css(`li[data-record-id="${uuid}"]`);
  reportByUUID: uuid => module.exports.list().all(matchedListItems).first(),
  reportsByUUID: uuid => module.exports.list().all(matchedListItems),
```
...but then realized this is all inline. I'm tempted to say "eh, nevermind, let's leave it for now" but this is still pretty quick to make easier on the reader. Similar to how lines 15 and 16 work, please just make functions for `reportByUUID` and reportsByUUID with the logic in them (not all inline here). Then, a nice benefit is that the implementation of `reportByUUID` will just be to call `reportsByUUID` and then call `first` on the result.

2021-02-09 21:51 UTC, newtewt commented
I updated to pull the function out and just make calls to that instead of in-lining. Last review maybe @craig-landry ?

2021-02-09 21:59 UTC, craig-landry approved these changes
lgtm. thanks for doing the cleanup work on existing stuff along the way!

2021-02-10 14:36 UTC, merged