86 registration by sms async
medic/cht-core pull request #6912
Opened 2021-02-10 16:18 UTC by newtewt

# Description

async/await and angular10changes for registrations-by-sms

https://github.com/medic/angular10-migration/issues/86

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-02-10 21:04 UTC, craig-landry requested changes

2021-02-10 21:04 UTC, craig-landry commented on tests/e2e/registration-by-sms.js
> +      await checkScheduledTask(3, 'ANC Reminders LMP:3', `LMP ${expectedDate.locale('sw').format(dateFormatString)}`);
Thanks :)

2021-02-10 21:43 UTC, newtewt commented on tests/e2e/forms/submit-delivery-form.specs.js
> +    await docs.map(async doc => {await utils.saveDocNative(doc); });
I actually ran into this same situation on the issue I was working on today and implemented this. I will update it here.

2021-02-11 21:52 UTC, craig-landry approved these changes

2021-02-12 14:30 UTC, merged