Migrates africas-talking.js and enables medic-collect.js
medic/cht-core pull request #6949
Opened 2021-02-18 04:48 UTC by dianabarsan

# Description

https://github.com/medic/angular10-migration/issues/78
https://github.com/medic/angular10-migration/issues/85

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-02-18 06:03 UTC, dianabarsan commented
hey @newtewt 
Please have a look. Thanks for your time!

2021-02-18 14:13 UTC, newtewt requested changes
Cool! Some minor changes about moving the Page objects.

2021-02-18 14:13 UTC, newtewt commented on tests/e2e/africas-talking.js
> +      return submitSms({ from: '+64271234567', text: 'hello', id: 'a' });
We can make this a nice one line by omitting the return.

`beforeEach(() => submitSms({ from: '+64271234567', text: 'hello', id: 'a' }));`

2021-02-18 14:13 UTC, newtewt commented on tests/e2e/africas-talking.js
> +    afterEach(() => {
Same as above, 

`afterEarch(() => utils.deleteDoc(savedDoc));`

2021-02-18 16:43 UTC, dianabarsan commented on tests/e2e/africas-talking.js
> +      await helper.waitElementToBeVisibleNative(element(by.css('#message-list li:first-child')));
Yea, you've added a lot of these in your PR.
I think it's better to merge that one 1st and then see what's left to be added from this one. :)

2021-02-22 16:53 UTC, dianabarsan commented
Could you have another look, @newtewt ? I was lucky to finally get no flakes and a green build!

2021-02-22 16:58 UTC, newtewt approved these changes
Nice! Feel free to merge.

2021-02-22 17:50 UTC, merged