6811 Fix targets with property "passesIfGroupCount.gte" counting 'pass:false'
medic/cht-core pull request #7015
Opened 2021-03-16 09:31 UTC by njogz

# Description

Fix a bug where the incorrect target was being shown for targets that use `passesIfGroupCount.gte`

medic/cht-core#[6811]

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-03-16 14:09 UTC, dianabarsan requested changes
Nice work! Thanks for fixing this. I left a couple of suggestions inline.

2021-03-16 14:09 UTC, dianabarsan commented on shared-libs/rules-engine/test/target-state.spec.js
> +        mockEmission({ _id: 'd', groupBy: '1', pass: false }),
Please add another group here that has 2 emissions, one passing and one failing, to prove that this group doesn't count as passed.

2021-03-17 08:49 UTC, njogz commented on shared-libs/rules-engine/src/target-state.js
> +        .reduce(reducer, {});
Nice! I have made the change.

2021-03-17 08:50 UTC, njogz commented
@dianabarsan thanks for the suggestions. I have made the requested changes. Please have another look when you can.

2021-03-17 12:08 UTC, dianabarsan approved these changes
Great work!

2021-03-24 18:37 UTC, merged