Refactor conf file
medic/cht-core pull request #7132
Opened 2021-06-09 02:30 UTC by ngaruko

# Description

Trying to remove all non-protractor functions from conf.js for reuse as we switch to new framework.

medic/cht-core#[number]

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-06-09 11:20 UTC, dianabarsan requested changes
Nice work! I just have some suggestions about readability and clarity.

2021-06-09 11:20 UTC, dianabarsan commented on tests/conf.js
> +      args: ['--window-size=1024,768','--headless','--disable-gpu'],
I think the spaces you removed here made the text more readable.

2021-06-09 11:20 UTC, dianabarsan commented on tests/conf.js
> +      utils.saveBrowserLogs();
I think we need to add a return statement here.

2021-06-09 11:20 UTC, dianabarsan commented on tests/utils.js
> +  },
I think we shouldn't inline these large function directly in the export. It makes browsing the file a lot harder. Please make these separate `consts` and export the variables. 
This applies to prepServices, login (which we should also rename to something more specific like "browserLogin"),  setupUser and saveBrowserLogs

2021-06-09 11:20 UTC, dianabarsan commented on tests/utils.js
> +const runAndLog = (msg, func) => {
I think we should rename this to signal that these are API startup messages.

2021-06-10 07:22 UTC, dianabarsan approved these changes
Great work! Aside from some missing/extra blanks around signs, before parentheses etc (which improve readability), this is perfect.

2021-06-10 17:41 UTC, newtewt commented
I pushed a commit that does the clean up around spacing. I want to consume this in the webdriver migration branch and will merge once the build passes.

2021-06-10 18:30 UTC, merged