Use mocha for server tests
medic/cht-core pull request #7155
Opened 2021-06-17 06:44 UTC by ngaruko

# Description

[description]

medic/cht-core#[number]

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-06-22 11:26 UTC, dianabarsan requested changes
Nice work!! I left a couple of recommendations inline.

2021-06-22 11:26 UTC, dianabarsan commented on tests/utils.js
> +const prepServicesNative = async () => {
I think we shouldn't just add all this duplicated code, and simply refactor the code that already exists. 
Also "native" isn't an appropriate suffix here, it doesn't communicate what the difference is between this function and `prepServices`.

2021-06-22 13:28 UTC, newtewt commented on .github/workflows/build.yml
> +    - name: Get Docker Hub username
I looked into reusable steps and sadly it's not supported yet. We could rearchitect our builds to use composite steps but that requires them either being shell or JavaScript code. Which isn't bad.

2021-06-23 01:37 UTC, ngaruko commented on tests/integration/hooks.js
> +    await utils.prepServicesNative();
The `beforeAll` in this root hook runs only ONCE at the beginning of the test suite. In the spec, `before` is the one that runs the before all tests.

2021-06-23 04:07 UTC, ngaruko commented on tests/integration/api/controllers/export-data-2.js
> +      }).then(done()));
for some reason Im getting timeout errors until I add `done` on this and some other specs

2021-06-23 17:33 UTC, garethbowen commented on tests/integration/api/controllers/export-data-2.js
> +      }).then(done()));
I think you need to make sure you return the promise. I think if you add a return on the first line of the test it'll just work, eg:

```
return utils.request({ path: '/api/v2/export/reports' }).then(result => {
```

2021-06-28 09:52 UTC, dianabarsan commented on .github/workflows/build.yml
> +    - name: Get Docker Hub username
Voting for Javascript to be more platform agnostic.

2021-06-28 12:51 UTC, dianabarsan requested changes
Awesome work!! I just left a few recommendations and questions inline.

2021-06-28 12:51 UTC, dianabarsan commented on tests/utils.js
> +    await setUserContactDoc();
Umm setting the userContactDoc doesn't make a lot of sense here. How come this is getting unset, or needs to be set? These docs should be always skipped on the "mass" deletion.

2021-06-28 12:51 UTC, dianabarsan commented on tests/utils.js
> +  }
I'm not sure I understand why this is needed. Why do we need to `listenForApi()` again? 
Also, the last line in this file is to set the user contact doc. I think it should work just fine without this condition.

2021-06-28 12:51 UTC, dianabarsan commented on tests/utils.js
> +const hasModal = async () => await element(by.css('#update-available')).isPresent();
You don't need async + await here. returning the promise is enough: 
```suggestion
const hasModal = () => element(by.css('#update-available')).isPresent();
```

2021-06-28 12:51 UTC, dianabarsan commented on tests/integration/api/server.js
> +      expect(bodyOne).to.equal(png);
```suggestion
      const getAttachmentOptions = { uri: '/sample_doc2/attach?rev=' + body.rev };
      const { res, body: attachmentBody } = await requestWrapper(getAttachmentOptions);
      expect(res.headers[ 'content-type' ]).to.equal('image/png');
      expect(res.headers[ 'content-encoding' ]).to.be.undefined;
      expect(attachmentBody).to.equal(png);
```

2021-06-28 12:51 UTC, dianabarsan commented on tests/integration/api/server.js
> +        .then(() => assert.fail('should have thrown'))
is `assert` a global here? Can we include it in the require, so we're 100% sure which `assert` we're using?

2021-07-01 11:18 UTC, dianabarsan approved these changes
Awesome work!

2021-07-02 01:16 UTC, merged