Hydrate contact and facility in API userSettings
medic/cht-core pull request #7191
Opened 2021-07-14 05:35 UTC by dianabarsan

# Description

Hydrate user's contact and facility when getting user settings. 
Use all subjects from user's contact and facility when checking if a report is sensitive. 

medic/cht-core#6660

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-07-14 17:05 UTC, dianabarsan commented
Please review, @latin-panda . Thanks!

2021-07-15 08:19 UTC, latin-panda requested changes
Nice job! I left a couple of minor suggestions in line :)

2021-07-15 09:37 UTC, dianabarsan commented on api/tests/mocha/auth.spec.js
> +      return auth.getUserSettings({ name: 'steve' }).catch(err => {
yes! good catch!

2021-07-16 02:29 UTC, latin-panda approved these changes
Nice Job!✨✨

2021-09-21 06:53 UTC, merged