78 display tab text
medic/cht-core pull request #7201
Opened 2021-07-19 04:04 UTC by ngaruko

# Description

[description]

https://github.com/medic/medic-release-testing/issues/78

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-07-20 16:07 UTC, dianabarsan requested changes
Nice work! I left a couple of comments inline.

2021-07-29 21:44 UTC, ngaruko commented on tests/mobile/common/common.specs.js
> +      await browser.driver.manage().window().setSize(389, 500);
done

2021-07-29 21:45 UTC, dianabarsan reviewed
I think I spotted something that might fix your build. Also, please rebase off of master for the driver version fix.

2021-08-03 16:18 UTC, dianabarsan requested changes
One idea in line about the failing e2e tests.

2021-08-03 16:18 UTC, dianabarsan commented on tests/mobile/common/common.specs.js
> +      await commonElements.waitForLoaderToDisappear(200000);
I think this is an extreme timeout. It also looks like all tests that follow this one fail with an error about not being able to load settings. 
I think you need to do this in the afterAll of this test: 
1. Delete the user (with utis.deleteUsers)
2. Logout and login as admin

2021-08-05 12:12 UTC, dianabarsan approved these changes
Awesome work!!

2021-08-05 20:32 UTC, merged