Streamline release issue template
medic/cht-core pull request #7216
Opened 2021-07-27 02:46 UTC by garethbowen

# Description

Updated based on our discussion in the product team leaders call. If/when this passes I'll copy the templates to the other repos.

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-07-28 19:35 UTC, craig-landry requested changes

2021-07-28 23:48 UTC, garethbowen commented on .github/ISSUE_TEMPLATE/z_release_major.md
> +# Planning - Manager
That's a great question. I think I was trying to make it clear it wasn't the role "Product Manager" but could be anyone. Looking over the list of action items again I wonder if it's unnecessary to include a "role" as I'd be quite happy with an engineer doing it. How do you feel about removing all role info?

2021-07-29 12:09 UTC, craig-landry commented on .github/ISSUE_TEMPLATE/z_release_major.md
> +# Planning - Manager
I like having the role on there actually. I agree that anyone could do many of the tasks, but that kind of just makes it nobody's job to do. I prefer the clarity.

An option that could work both ways here would be that those roles are defaults, but people are free to override those via informal chats as needed/desired.

2021-07-29 19:04 UTC, garethbowen commented on .github/ISSUE_TEMPLATE/z_release_major.md
> +# Planning - Manager
Ok. Do you think "Product Manager" is the right role and I should revert this change?

2021-07-29 19:42 UTC, craig-landry commented on .github/ISSUE_TEMPLATE/z_release_major.md
> +# Planning - Manager
Yeah, I think that's the most logical default.

2021-07-29 22:48 UTC, craig-landry approved these changes

2021-07-29 23:25 UTC, merged