71 targets aggregates
medic/cht-core pull request #7232
Opened 2021-08-05 03:20 UTC by ngaruko

# Description

https://github.com/medic/cht-release-testing/issues/71

medic/cht-core#[number]

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-09-08 14:06 UTC, newtewt requested changes
Nice! I've added a few things in line. Sadly we cannot merge this until we can reliably get past the race condition. 

https://github.com/medic/cht-core/issues/7242

2021-09-08 14:06 UTC, newtewt commented on tests/page-objects/analytics/analytics.wdio.page.js
> +const listModule = module => $(`.mm-navigation-menu li a[href="${module}"]`);
There seems to be a lot of unused code in this PR. Can you remove what's not used?

2021-09-08 14:06 UTC, newtewt commented on tests/e2e/targets/targets-aggregates.wdio-spec.js
> +    expect(await (await analyticsPage.aggregateHeading()).getText()).toBe('New pregnancies');
Using the wdio expect for `toHaveText` you can get rid of the call to `getText()`


`expect(await analyticsPage.aggregateHeading()).toHaveText('New pregnancies');`

https://webdriver.io/docs/api/expect-webdriverio/#tohavetext

2021-09-09 00:27 UTC, ngaruko commented on tests/e2e/targets/targets-aggregates.wdio-spec.js
> +  name: 'contact_' + Date.now(),
Actually thinking of extending this for the next use case and create multiple chws but for this pr, the default suffices.

2021-11-02 22:11 UTC, ngaruko commented
Automated [here](https://github.com/medic/cht-core/blob/master/tests/e2e/target-aggregates.spec.js)

2021-11-02 22:11 UTC, closed without merging