use docker for selenium
medic/cht-core pull request #7283
Opened 2021-08-31 05:13 UTC by ngaruko

# Description

Use docker for selenium to avoid session creation issue due to version mismatch between the driver and the browser.

medic/cht-core#[7282]

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-08-31 13:18 UTC, newtewt requested changes
The docs read as if these are going to run in a headed browser because they've set it up to do so and then we set it to run headless in the `conf.js`. We normally run CI in headless and some people use headed browsers when debugging. Please add docs on how to run these so if someone is debugging they can run in a headed browser locally. Also, disable the "Xvfb" as described in the [docs ](https://github.com/SeleniumHQ/docker-selenium#running-in-headless-mode) for headless runs.  

Once we've migrated to WDIO this should no longer be an issue.

2021-08-31 13:18 UTC, newtewt commented on Gruntfile.js
> +          'docker run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:3.141.59-yttrium > tests/logs/webdriver.log & ' +
Looks like the [docs ](https://github.com/SeleniumHQ/docker-selenium#--shm-size2g) removed the volume mounting in favor of setting a cli arg. 

`docker run -d -p 4444:4444 --shm-size="2g" selenium/standalone-chrome:3.141.59-yttrium > tests/logs/webdriver.log &`

2021-09-01 14:40 UTC, mrsarm requested changes
Looks good, just a minor suggestion and a question.

2021-09-01 14:40 UTC, mrsarm commented on tests/constants.js
> +}
These nested `for`s:

```js
for (const name of Object.keys(nets)) {
  for (const net of nets[name]) {
```

Can be joined in one:

```js
for (const [name, net] of Object.entries(nets)) {
```

2021-09-01 14:40 UTC, mrsarm commented on Gruntfile.js
> -          'scripts/e2e/start_webdriver.sh'
Are we going to remove the `start_webdriver.sh` script? or are we keeping it because it's used/useful in other scenarios?

2021-12-12 22:48 UTC, ngaruko commented
No longer needed

2021-12-12 22:48 UTC, closed without merging