7289 refactor e2e sentinel tests
medic/cht-core pull request #7306
Opened 2021-09-10 03:49 UTC by ngaruko

# Description

[description]

medic/cht-core #7289 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-09-13 15:02 UTC, newtewt requested changes
Nice work on moving over. We can get in line a bit better with chai's expects instead of to.equal everywhere. As it makes more sense to follow the paradigm's within chai instead of what could essentially be `actualValue === expectedValue`

A few callouts that can be updated.

Use the `to.be.empty` on array an empty array check. 

From
 `expect(doc.tasks.length).to.equal(0);`
To
 `expect(doc.tasks).to.be.empty;`
 
https://www.chaijs.com/api/bdd/#empty

Use `to.have.lengthOf(1)` when checking length
From 
`expect(updated[0].tasks.length).to.equal(1);`
To 
`expect(updated[0].tasks).to.have.lengthOf(1)`

Use `to.be.true` or `to.be.false` for true false checks

From 
 `expect(info.transitions.update_clinics.ok).to.equal(true);`
 To 
 `expect(info.transitions.update_clinics.ok).to.be.true;`

2021-09-13 23:38 UTC, ngaruko commented on tests/integration/hooks.js
> +    await utils.prepServices({suite:'web'});
refactored this. It is just a boolean atm and it just load the settings.

2021-09-14 04:50 UTC, ngaruko commented on tests/utils.js
> +      }, 6000);
It is quite arbitrary. I did a few increments and settled with 6o sec. Looks stable enough.

2021-09-14 20:16 UTC, ngaruko commented on tests/e2e/sentinel/queue.spec.js
> +  }).timeout(300000);
removed that and it passed build. Will monitor

2021-09-15 13:33 UTC, newtewt approved these changes
Nice job moving these over.

2021-09-15 23:06 UTC, merged