Migrate concatenate strings
medic/cht-core pull request #7333
Opened 2021-09-22 03:53 UTC by ngaruko

# Description

[description]

medic/cht-core #7302 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2021-11-04 06:29 UTC, dianabarsan requested changes
Nice work! Just some minor observations. 
Also, as part of the Enketo-core upgrade, we will not be supporting this deprecated behavior and this test will be removed: [link to removed file](https://github.com/medic/cht-core/pull/7256/files?authenticity_token=pP89Nv%2FzoIhAUS6MtBKnHeR4MgBgRzw4z6ahdbGtVidurIV2a%2F%2BJ4%2FMrj6fBy5wNdhjkJseAtcnP2RpRqTNSDQ%3D%3D&file-filters%5B%5D=.MD&file-filters%5B%5D=.html&file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.less&file-filters%5B%5D=.md&file-filters%5B%5D=.patch&file-filters%5B%5D=.png&file-filters%5B%5D=.properties&file-filters%5B%5D=.scss&file-filters%5B%5D=.ts&file-filters%5B%5D=.xlsx&file-filters%5B%5D=.xml&file-filters%5B%5D=.xsl#diff-74df930981a5978977973a95e45af31a0f3a11f90dfa5786982722e29878f25bL1)

2021-11-04 06:29 UTC, dianabarsan commented on tests/page-objects/forms/generic-form.wdio.page.js
> +const formByHref = (href) => {
I think this is a little misleading. We're actually passing a form id, not a "href" here. 
I think we should rename this to: `getFormLinkElementById` to be extra clear on what it does.

2021-11-04 06:29 UTC, dianabarsan commented on tests/page-objects/forms/generic-form.wdio.page.js
> +const selectForm = async (formId, nonAdminUser = false) => {
We already have an `openForm` method exposed in reports.wdio.page which we could use instead and not have duplicated logic.

2021-11-04 06:29 UTC, dianabarsan commented on tests/page-objects/forms/concatenate-strings.wdio.page.js
> +const reportContent = () =>$('div#reports-content');
Please use consistent spacing here: 
```suggestion
const reportContent = () => $('div#reports-content');
```

2021-11-04 06:29 UTC, dianabarsan commented on tests/e2e/concatenate-xpath-strings.wdio-spec.js
> +  beforeEach(() => concatenateStrings.configureForm(userContactDoc));
There's only one test, we can just use `before` and not `before` and `beforeEach`.

2021-11-04 06:29 UTC, dianabarsan commented on tests/e2e/concatenate-xpath-strings.wdio-spec.js
> +  afterEach(() => utils.revertDb([], true));
I believe this is not needed anymore. We already have a global `after` cleanup and there's just one test suite here.

2021-11-18 12:33 UTC, dianabarsan reviewed
@ngaruko whoops it looks like the merge went wrong and there are 28,000 line changes. Couldyou please fix the merge so only your changes appear in the diff? 
Thanks!

2021-11-21 20:34 UTC, ngaruko commented
@dianabarsan some rebasing gone wrong! Fixed that!

2021-11-22 09:02 UTC, dianabarsan approved these changes
Awesome possum

2021-11-23 03:29 UTC, merged