Re-set the enketo form's language when a DOM node is added to the form
medic/cht-core pull request #7520
Opened 2022-02-15 18:36 UTC by m5r

# Description

Leverage [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver#browser_compatibility) to react to DOM changes to the form and re-set the enketo form's language.  
This fix won't be needed anymore once the enketo uplift gets merged medic/cht-core#7256

medic/cht-core#7515

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2022-02-24 17:08 UTC, m5r commented
@jkuester can you please review this fix please? Thanks!

2022-02-24 18:32 UTC, garethbowen requested changes
As Josh is on leave and this is a pressing issue, I've jumped in to review - hope that's ok!

This looks great. The change event will fire quite often - have you checked that the performance is ok?

Other than that I have a few comments inline but nothing major.

2022-02-24 18:32 UTC, garethbowen commented on tests/e2e/forms/repeat-form.wdio-spec.js
>  };
This is mostly a repeat of the lines above - let's make a function that takes the filename, id, and title (or make the title the same as the id?) to save the duplication.

2022-02-24 18:32 UTC, garethbowen commented on webapp/src/ts/services/enketo.service.ts
> +        // re-set the enketo form's language when a DOM node is added/removed to the form
I think this comment is out of date. If I'm understanding correctly, the `change` event fires when an input in the form is updated by the user, not when a DOM node is added or removed.

2022-02-24 18:32 UTC, garethbowen commented on webapp/tests/karma/ts/services/enketo.service.spec.ts
> +        html: document.createElement('div'),
I don't think you need this any more.

2022-02-25 17:44 UTC, jkuester reviewed
I did have a look through these code changes since they are dealing with the Enketo functionality. I don't really have anything to add besides what Gareth has already pointed out, but I did test your new `repeat-translation-count` form with the new Enketo version and verified that it still works as expected.  :+1:

2022-02-28 15:20 UTC, m5r commented
Thanks for the feedback @garethbowen @jkuester

I was frustrated with the solution I came up with and thought about it all weekend :joy:  
I decided to re-introduce the `MutationObserver` to trigger the language change when both conditions are met:
- a DOM node is added to the form -- `MutationObserver` picked up at least one new node in the form
- the form has been edited -- the form `change` event was triggered
This fixes our translation issue but also put less strain on the phones' CPU by asking Enketo fewer times to change the form's language

2022-03-01 00:08 UTC, garethbowen approved these changes
The new approach looks reasonable. I worry with state like this that further changes may regress if someone forgets to set it, but because we'll remove the code in 4.0.0 I think the risk is minimal.

2022-03-01 14:06 UTC, jkuester approved these changes

2022-03-01 16:49 UTC, merged