Removing unused parameters, fixing data type in interface and fixing …
medic/cht-core pull request #7546
Opened 2022-03-04 07:52 UTC by latin-panda

# Description
Sending these quick fixes in a separate PR for fast merging into the main branch, because I'm working on a feature release that might take long to merge into main. 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2022-03-11 08:03 UTC, latin-panda commented
@dianabarsan can you please have a look at this small fixes? I'm guessing we don't need to AT these, right?

2022-03-11 08:17 UTC, dianabarsan requested changes
Just a few stragglers. 
If it were just for the changed paths, I would agree that this doesn't need AT (since app building should fail if any of the paths is incorrect). 
However, making the change in the EnketoService interface does make AT required, since that is a functional change, and I don't think we cover forms with media elements in our e2e tests.

2022-03-11 08:17 UTC, dianabarsan commented on webapp/src/ts/modules/configuration-user/configuration-user.routes.ts
> +import { ConfigurationUserComponent } from './configuration-user.component';
```suggestion
import { ConfigurationUserComponent } from '@mm-modules/configuration-user/configuration-user.component';
```

2022-03-11 08:17 UTC, dianabarsan commented on webapp/src/ts/modules/about/about.routes.ts
> +import { AboutComponent } from './about.component';
```suggestion
import { AboutComponent } from '@mm-modules/about/about.component';
```

2022-03-11 08:17 UTC, dianabarsan commented on webapp/src/ts/modules/error/error.routes.ts
>  import { ErrorComponent } from './error.component';
```suggestion
import { ErrorComponent } from '@mm-modules/error/error.component';
```

2022-03-11 08:17 UTC, dianabarsan commented on webapp/src/ts/modules/home/home.routes.ts
>  import { HomeComponent } from './home.component';
```suggestion
import { HomeComponent } from '@mm-modules/home/home.component';
```

2022-03-14 04:55 UTC, latin-panda commented on webapp/src/ts/modules/configuration-user/configuration-user.routes.ts
> +import { ConfigurationUserComponent } from './configuration-user.component';
Done

2022-03-14 04:56 UTC, latin-panda commented on webapp/src/ts/modules/about/about.routes.ts
> +import { AboutComponent } from './about.component';
Done

2022-03-14 04:56 UTC, latin-panda commented on webapp/src/ts/modules/error/error.routes.ts
>  import { ErrorComponent } from './error.component';
Done

2022-03-14 04:57 UTC, latin-panda commented on webapp/src/ts/modules/home/home.routes.ts
>  import { HomeComponent } from './home.component';
Done

2022-03-14 06:00 UTC, latin-panda commented
Thanks @dianabarsan, I've applied the suggestions and created a ticket for better AT tracking. Please have a look again when you have time :)

2022-03-14 06:15 UTC, dianabarsan approved these changes
🌟

2022-03-14 06:15 UTC, dianabarsan approved these changes
🌟

2022-03-22 02:09 UTC, merged