Remove continuous replication API support
medic/cht-core pull request #7582
Opened 2022-04-06 06:51 UTC by dianabarsan

# Description

medic/cht-core#4874

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2022-04-19 18:52 UTC, dianabarsan commented
Mind having a look at this one, @garethbowen ? Thanks a lot!

2022-04-19 20:59 UTC, garethbowen requested changes
Nice!

Some minor comments inline.

Does this need to be marked as a breaking change? What would the experience be if someone upgraded from before continuous replication was deprecated (ie: 3.3.0 or below) to 4.0.0? Would the replication fail, and if so, would the service worker still get updated and then replication resume correctly after restart?

2022-04-19 20:59 UTC, garethbowen commented on api/src/controllers/changes.js
> +  });
Nit: Good chance to use the auto return arrow function.

```suggestion
  return initFeed(req, res)
    .then(feed => getChanges(feed));
```

2022-04-19 20:59 UTC, garethbowen commented on api/src/controllers/changes.js
> -}
YES!

2022-04-19 20:59 UTC, garethbowen commented on config/covid-19/app_settings.json
>    },
Let's just remove this `changes_controller` property altogether, seeing as it's using the default anyway.

2022-04-19 20:59 UTC, garethbowen commented on config/covid-19/app_settings/base_settings.json
>    },
Ditto.

2022-04-19 20:59 UTC, garethbowen commented on config/default/app_settings.json
>    },
And here.

2022-04-19 20:59 UTC, garethbowen commented on tests/config.default.json
>    },
One more time.

2022-04-19 20:59 UTC, garethbowen commented on tests/e2e/api/controllers/_changes.spec.js
> +            // because we still process pending changes,xit's not a given we will receive only 4 changes.
Find and replace?

```suggestion
            // because we still process pending changes, it's not a given we will receive only 4 changes.
```

2022-04-19 20:59 UTC, garethbowen commented on tests/e2e/api/controllers/_changes.spec.js
> +        // revert steve, he didn't likexit in bobville
:joy: 

```suggestion
        // revert steve, he didn't like it in bobville
```

2022-04-19 20:59 UTC, garethbowen commented on tests/e2e/api/controllers/_changes.spec.js
> +          // can't use assertChangeIds here becausexit ignores deletes
```suggestion
          // can't use assertChangeIds here because it ignores deletes
```

2022-04-21 16:47 UTC, dianabarsan commented
> Does this need to be marked as a breaking change? 

The endpoint has not been used since `3.3.0`. 

> What would the experience be if someone upgraded from before continuous replication was deprecated (ie: 3.3.0 or below) to 4.0.0? Would the replication fail, and if so, would the service worker still get updated and then replication resume correctly after restart?

Replication does not fail. The controller will treat the 3.3.0 initiated longpoll as a normal request and respond immediately, even if there are no changes. The app will just request changes again immediately. So worst case is that the server gets many changes requests over and over.

2022-04-21 16:52 UTC, dianabarsan commented
The biggest problem that I had with 3.3.0 upgrade was that the whole code to show the update modal is wrapped in a condition that tests for `window.applicationCache`: https://github.com/medic/cht-core/blob/3.3.x/webapp/src/js/controllers/inbox.js#L686

Latest Chrome fails that condition (window.applicationCache is undefined). Firefox still has _something_, but it doesn't actually cache anything? I tweaked to code locally to show the modal regardless of the appcache update - so getting the change would be enough, and the upgrade was successful. 

I think the appcache problem is quite separate from this issue. The endpoint did send the modal triggering changes.

2022-04-21 23:52 UTC, garethbowen commented
Ok so if they haven't also updated their browser the it should just work and we don't need to label it breaking.

However, if they have updated their browser, then when they load the site then Chrome will bypass the appcache (because it doesn't know what that is), and download the latest code directly from the server. That will register the SW and everything will be sorted, right? Assuming they have an internet connection, of course.

2022-04-21 23:53 UTC, garethbowen approved these changes

2022-04-21 23:53 UTC, garethbowen commented
Great work! Happy to continue discussion browser upgrade headaches but I don't think it blocks this issue...

2022-06-02 05:32 UTC, merged