Title test too long for mobile 340px view port width - Apply ellipsis text overflow
medic/cht-core pull request #7681
Opened 2022-07-19 05:43 UTC by elvisdorkenoo

# Title test too long for mobile 340px view port width 

This PR fix the issue 6028, clipping the the header of Task, Contact and Report tabs when the title is too long for mobile view.

# To test this PR
- [ x] : Use a mobile device, or developer tools, toggle device to mobile, or set view port width to 340px(more or less)
- [ x] : Go to Task, Contact and/or Report tab
- [ x] : Check if the overflow text of too long titles is replaced by ellipsis (...)
- [ x] : Check if the overflow text is forced visible when the header is in focus

medic/cht-core#6028

# Code review checklist

- [ x] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ x] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ x] Tested: Unit and/or e2e where appropriate
- [ x] Internationalised: All user facing text
- [ x] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2022-07-19 07:02 UTC, latin-panda requested changes
Cool! I left a couple of comments inline :)

2022-07-20 04:08 UTC, latin-panda commented on webapp/src/css/inbox.less
> +      :hover {
Based on yesterday convo, we won't develop a way to visualise the full title (for now), so you can remove this hover block. :)

2022-07-20 05:10 UTC, elvisdorkenoo commented on webapp/src/css/inbox.less
> +      :hover {
Yeah, that's correct, thank you. I'll also update the test steps to remove it as well.

2022-07-20 06:53 UTC, latin-panda approved these changes
Nice! 
Please move the ticket to "Ready for AT" and notify QA that this is ready for testing. 
Hopefully we can make it on time for 3.16.x release :)

2022-07-21 03:11 UTC, latin-panda commented
@elvisdorkenoo I noticed this PR is ready for merge 🎉 

The following steps are:
- Select "Squash and merge", this way all your commits are compressed into one and allow us to keep the commit history clean.
- Type a meaningful commit message. This is very useful to others when researching about changes in the code and leaves a nice impression from the author 😎 the cherry on the cake. 
```
Ticket: [ link ]

This commit:
- Adds feature A 
- Adds validations to A
- Removes old code that was .......
```
- Move the ticket to "Done"
- Notify the release manager, this case Njuguna, that this ticket is ready to be included in 3.16.x
- 
Thanks!

2022-07-21 13:07 UTC, elvisdorkenoo commented
@latin-panda 
Thank you for the tips, I'm on it 👍🏽
Please should we close the issue as well ?

2022-07-21 13:13 UTC, latin-panda commented
@elvisdorkenoo I think when you move the issue to "Done", it will close it automatically.
Once the PR is "Squashed and merged" you just need to delete the branch, please! :)

2022-07-21 15:41 UTC, merged