improve(#8189): Convert Add/Edit User modal to page
medic/cht-core pull request #8192
Opened 2023-04-19 23:05 UTC by isis-meng

# Description

Convert the Add/Edit User modal into a page with a unique URL.

medic/cht-core#8189

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* __CHT_CORE_COMPOSE_URL__
* __COUCH_SINGLE_COMPOSE_URL__
* __COUCH_CLUSTER_COMPOSE_URL__

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2023-04-19 23:17 UTC, isis-meng commented
Some questions I have:
- What is the most appropriate way to convert error messages from modal-specific formats to be displayed for pages? (eg., lines 459-460, 474-475 in `edit-user.js`)
- What is a good way to allow information to persist in the form between refreshes?

Any advice would be really appreciated, thank you!

2023-04-26 01:27 UTC, garethbowen requested changes
Thanks! This is looking great.

I've left a few tips inline.

> What is a good way to allow information to persist in the form between refreshes?

What information do you want to persist? Usually on web forms I would expect information to be lost.

2023-04-26 01:27 UTC, garethbowen commented on admin/src/js/controllers/edit-user.js
> +              $log.error(value, err);
`$scope.setError` used to show the error in the footer of the modal so the user could see what went wrong. It looks like this is just putting it in the console which most users won't check. Let's make sure the user gets some feedback.

2023-04-26 01:27 UTC, garethbowen commented on admin/src/js/main.js
> +    })
AngularJS does some magic with these state names, so if you have them as dot separated then it understands that the two pages are related. I think it'll be simpler like this...

```suggestion
    .state('user.edit', {
      url: '/edit/:name', // now that it's a child the "/users" part is included automatically.
      controller: 'EditUserCtrl',
      templateUrl: 'templates/edit_user.html',
      params: {
        user: null,
        name: null
      },
    })
```

NB: I haven't tested this at all so you may need to tweak it a bit!

2023-04-26 01:27 UTC, garethbowen commented on admin/src/templates/index.html
> +            <li ng-class="{'active-nav': checkActive('users')}" mm-auth="can_configure"><a ui-sref="users" translate>Users</a></li>
I don't think this change is needed if the state name is updated as per my previous suggestion.

2023-04-26 01:27 UTC, garethbowen commented on admin/src/js/controllers/edit-user.js
> +            $log.info("FIX ME ASYNC VALID")
If I recall correctly the `setError` function clears the "processing" state so the loading spinner goes away, the buttons are enabled again, and maybe sets some styling on the form. We'll want to include that styling here too.

2023-05-10 22:55 UTC, garethbowen commented
@isis-meng How are you getting on here? Is there anything I can do to help?

2024-02-15 12:21 UTC, garethbowen commented
Closing as ancient.

2024-02-15 12:21 UTC, closed without merging