chore(#8184): update replication performance suite to use new endpoints
medic/cht-core pull request #8398
Opened 2023-07-19 12:33 UTC by dianabarsan

# Description

medic/cht-core#8184

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* __CHT_CORE_COMPOSE_URL__
* __COUCH_SINGLE_COMPOSE_URL__
* __COUCH_CLUSTER_COMPOSE_URL__

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2023-07-25 23:03 UTC, ngaruko requested changes
Very interesting work here. Extremely impressed with the generateData function. Just one comment/suggestion, if it is at all feasible.

2023-07-25 23:03 UTC, ngaruko commented on tests/factories/cht/generate.js
> +const createData = ({ healthCenter, user, nbrClinics=10, nbrPersons=10 }) => {
wow... this is an extremely useful function 👍

2023-07-26 05:01 UTC, dianabarsan commented on tests/e2e/default/telemetry/telemetry.wdio-spec.js
> +      'metadata.day': moment().date() - 1, // we "rolled" back time to yesterday
This is already in `master` I think, and I "hotpatched" this branch. I'll just merge so this change doesn't get visible.

2023-07-28 02:03 UTC, ngaruko approved these changes
Looks good.

2023-07-28 10:05 UTC, merged