chore(#8390): modal migration to angular material's dialogs
medic/cht-core pull request #8441
Opened 2023-08-09 06:43 UTC by latin-panda

# Description

WIP

medic/cht-core#8390

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* __CHT_CORE_COMPOSE_URL__
* __COUCH_SINGLE_COMPOSE_URL__
* __COUCH_CLUSTER_COMPOSE_URL__

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2023-08-21 15:53 UTC, latin-panda commented on webapp/src/ts/modals/edit-user/confirm-password-updated.component.html
This modal is now a snackbar message.

2023-08-21 15:54 UTC, latin-panda commented on webapp/src/ts/modals/bulk-delete-confirm/bulk-delete-confirm.component.html
> -  <p *ngIf="deleteComplete">{{'bulkdelete.complete' | translate}}</p>
The message for when bulk delete is completed has been removed.

2023-08-21 16:17 UTC, latin-panda commented
@ngaruko @m5r, Can you please review it? 

Mokhtar, I know you're traveling; there is no rush. This is just a draft, and I still have a couple of things to finish:
- upload new translations 
- add more test coverage for new code. 

Many of these changes are updating the unit and e2e tests. I think @ngaruko can help review the e2e files, so you don't need to worry about those.

2023-08-23 15:53 UTC, latin-panda commented
@ngaruko Have you had time to look at this? Do you have any feedback?

2023-08-24 08:06 UTC, ngaruko requested changes

2023-08-24 08:06 UTC, ngaruko commented on tests/e2e/default/enketo/training-cards.wdio-spec.js
> +      'If you leave now, you will lose your progress and be prompted again later to complete it.'
Wondering if we could extract this text as a constant since it is quite long and used more than once?

2023-08-28 13:10 UTC, m5r approved these changes
Well done migrating this foundational common component without overengineering it :+1: 

No big change requested, just a few questions inlined

2023-08-30 07:56 UTC, latin-panda commented on tests/e2e/upgrade/upgrade.wdio-spec.js
> +// ToDo: Remove once 4.4 is released. Because it needs selectors targeting the previous cht version.
I've created one https://github.com/medic/cht-core/issues/8501. Thanks!

2023-08-30 07:56 UTC, latin-panda commented on webapp/src/ts/components/modal-layout/modal-layout.component.ts
Thank you! 🙂

2023-08-30 08:03 UTC, latin-panda commented on webapp/src/js/bootstrapper/translator.js
> +    SESSION_EXPIRED_DESCRIPTION: 'Su sesión ha expirado y usted ha sido desconectado. Por favor inicie sesión para continuar.', // eslint-disable-line max-len
Good idea! I've done it for the translation block

2023-08-30 08:07 UTC, latin-panda commented
Hi @ngaruko I've pushed your suggestion ([commit](https://github.com/medic/cht-core/pull/8441/commits/3971b93316d1674296c0885d234d05375601b558)). Please have a look

2023-08-31 01:37 UTC, ngaruko approved these changes
Looks good.
Thanks for updating e2e tests.

2023-08-31 02:52 UTC, merged