chore(#8264): restructured add-new-district.wdio-spec.js test
medic/cht-core pull request #8531
Opened 2023-09-07 21:01 UTC by tatilepizs

# Description

[description]

medic/cht-core#8264

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* __CHT_CORE_COMPOSE_URL__
* __COUCH_SINGLE_COMPOSE_URL__
* __COUCH_CLUSTER_COMPOSE_URL__

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2023-09-08 05:30 UTC, ngaruko approved these changes
Looks good. Tested a few times and it seems to be solid.
Thanks

2023-09-08 16:50 UTC, lorerod requested changes
This looks great @tatilepizs! Just a change request to make retries possible.

2023-09-08 16:50 UTC, lorerod commented on tests/e2e/default/contacts/add-new-district.wdio-spec.js
>    afterEach(() => sentinelUtils.waitForSentinel());
Please change this so retries are possible.
```suggestion
  afterEach(async () => {
    sentinelUtils.waitForSentinel();
    await utils.revertDb([/^form:/], true);
  });
```

2023-09-11 09:21 UTC, ralfudx approved these changes
Looks good to me... although not entirely sure about the hardcoded test variables but will be nice to have further discussions about them in future

2023-09-13 15:54 UTC, lorerod approved these changes
Gracias @tatilepizs !

2023-09-13 16:06 UTC, merged