fix(couchdb): checks cluster_finished before asserting completion
medic/cht-core pull request #8552
Opened 2023-09-16 11:25 UTC by fardarter

Since fixing the bug in `verify_membership(`), my cluster deployments have been failing to achieve `cluster_finished` state, getting stuck in `cluster_enabled`. This ensures that `'{"action": "finish_cluster"}'` is run before completion is asserted.

# Description

[description]

medic/cht-core#[number]

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# Compose URLs

If Build CI hasn't passed, these may 404:

* __CHT_CORE_COMPOSE_URL__
* __COUCH_SINGLE_COMPOSE_URL__
* __COUCH_CLUSTER_COMPOSE_URL__

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2023-10-18 02:52 UTC, garethbowen commented
Not sure how this slipped through the cracks, but @dianabarsan would you mind reviewing please?

2023-10-19 13:59 UTC, dianabarsan requested changes
Unfortunately, because of the way we use CouchDb, with a single replica, the cluster never reaches the `clustered_finished` state. 
This means that if we add this, we will try to finish the cluster every time we start couchDb. 

Once we add multiple replicas, we should definitely add this.

2023-10-19 14:05 UTC, fardarter commented
> Unfortunately, because of the way we use CouchDb, with a single replica, the cluster never reaches the `clustered_finished` state. This means that if we add this, we will try to finish the cluster every time we start couchDb.
> 
> Once we add multiple replicas, we should definitely add this.

It will only run if there are peer provides, which is the multiple node case, no?

2023-10-20 09:03 UTC, dianabarsan commented
> > Unfortunately, because of the way we use CouchDb, with a single replica, the cluster never reaches the `clustered_finished` state. This means that if we add this, we will try to finish the cluster every time we start couchDb.
> > Once we add multiple replicas, we should definitely add this.
> 
> It will only run if there are peer provides, which is the multiple node case, no?

It is the multiple node case, but in our case we do multi-node single replica, which makes the cluster be in `single_node_enabled`. 
You can observe this interaction on this branch: https://github.com/medic/cht-core/tree/cluster-demo

2023-10-20 09:21 UTC, fardarter commented
> > > Unfortunately, because of the way we use CouchDb, with a single replica, the cluster never reaches the `clustered_finished` state. This means that if we add this, we will try to finish the cluster every time we start couchDb.
> > > Once we add multiple replicas, we should definitely add this.
> > 
> > 
> > It will only run if there are peer provides, which is the multiple node case, no?
> 
> It is the multiple node case, but in our case we do multi-node single replica, which makes the cluster be in `single_node_enabled`. You can observe this interaction on this branch: https://github.com/medic/cht-core/tree/cluster-demo

Off the top of your head and before I dig, is there some fact I could check before running it?

2023-10-20 09:29 UTC, dianabarsan commented
I'm not sure what you mean, @fardarter . The PR just demonstrates my point via a new e2e test. You can also check your local cluster.

2023-10-20 10:29 UTC, fardarter commented
I mean is there some way to detect using the API which configuration should not prompt the finish call?

2023-10-20 11:06 UTC, dianabarsan commented
Yea, you can call the exact endpoint that the setup script you just changed calls and see what output you get when you setup CouchDb using our image and no additional settings.

2024-10-24 12:49 UTC, garethbowen commented
@fardarter Did Diana's respond resolve this issue or do you still want to get this merged?

2024-10-24 13:06 UTC, fardarter commented
> @fardarter Did Diana's respond resolve this issue or do you still want to get this merged?

I haven't followed up with a resolution. It seems the code is depending on the bug right now.

2025-07-07 00:06 UTC, closed without merging