fix(#5807): align target cards
medic/cht-core pull request #8948
Opened 2024-03-19 13:42 UTC by Benmuiruri

# Description

Updates the Targets page to align the `target` card to the columns

Closes #5807 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2024-03-20 08:27 UTC, latin-panda requested changes
Please test in 
- firefox
- chrome
- desktop, phone and tablet

2024-03-20 08:27 UTC, latin-panda commented on webapp/src/css/targets.less
> +  gap: 0 24px;
Please extract the 24 in a variable

2024-03-20 13:33 UTC, n-orlowski approved these changes
LGMT! 🎉

2024-03-21 05:44 UTC, latin-panda approved these changes
Thanks! LGTM!

2024-03-21 08:20 UTC, merged