chore(#8957): translate to spanish 900 to 1200
medic/cht-core pull request #8992
Opened 2024-04-08 13:45 UTC by latin-panda

# Description

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2024-04-09 20:53 UTC, lorerod requested changes

2024-04-10 02:19 UTC, latin-panda commented on api/resources/translations/messages-es.properties
> +report.pregnancy.lmp_date = Fecha FUM
Here I changed it to: Fecha de última menstruación

2024-04-10 02:27 UTC, latin-panda commented on api/resources/translations/messages-es.properties
> +patient\ id\ not\ found\ response = Envíe el siguiente mensaje de respuesta las validaciones pasan correctamente pero no hay ningún valor para el campo de Medic ID.
I missed some words. The English is: `Send the following response message if the validations pass but the Medic ID is not located.`
My understanding is: The message will be sent if 
- medic id is not found
- and all other validation passes

I changed it to: `Enviar el siguiente mensaje de respuesta, sí las validaciones pasan correctamente pero no se encontró el Medic ID.`
What do you think?

2024-04-10 02:32 UTC, latin-panda commented
Thanks @lorerod! I've resolved the feedback

2024-04-10 10:30 UTC, lorerod approved these changes
Thank you @latin-panda!

2024-04-10 11:09 UTC, merged