Use helm repo for cht-deploy
medic/cht-core pull request #8996
Opened 2024-04-09 12:53 UTC by nydr

# Description

- Depends on https://github.com/medic/helm-charts/pull/5
- Prerequisite for https://github.com/medic/cht-core/pull/8908

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2024-04-19 20:22 UTC, henokgetachew requested changes
I like the changes. Good job! 
Left a minor comment about keeping configuration here or a README file that contains a copy of the sample config.

2024-04-19 20:22 UTC, henokgetachew commented on scripts/deploy/helm/cht-chart/values.yaml
Whatever we choose, we need to update it when we update the `DEFAULT_CHART_VERSION` variable.

2024-04-22 12:02 UTC, nydr commented on scripts/deploy/helm/cht-chart/values.yaml
> something like `deployment-config.yaml`

I'd hope this could be solved through something like `helm show values` or a link to the charts values file to avoid having to keep two pages in sync

> update the `DEFAULT_CHART_VERSION` variable

This might lead to more overhead than ideal, I see two possible solutions
1. Set patch and perhaps minor version to wildcard, then this variable only needs to be updated when major changes are done to the chart
2. Set the chart version in values.yaml, so the version of a specific deployments gets locked to a chart version once initially created but any updates will need to update the yaml file as well

2024-04-23 15:33 UTC, henokgetachew commented on scripts/deploy/helm/cht-chart/values.yaml
>I'd hope this could be solved through something like helm show values or a link to the charts values file to avoid having to keep two pages in sync

Agreed.

re: `DEFAULT_CHART_VERSION`, I think I like the 1st option better.

2024-04-23 15:33 UTC, henokgetachew approved these changes

2024-04-23 16:13 UTC, henokgetachew commented on scripts/deploy/helm/cht-chart/values.yaml
Okay I have filed a [ticket](https://github.com/medic/cht-core/issues/9040) for adding an `init` command for `cht-deploy`. This will avoid us having to keep two pages in sync like you said.

2024-04-29 07:28 UTC, nydr commented on scripts/deploy/helm/cht-chart/values.yaml
Merging without setting version to wildcard on patch level FYI @henokgetachew. That can be added on the next update so this PR isn't blocking future development

2024-04-29 07:32 UTC, merged