chore(#9080): adds logger shared lib
medic/cht-core pull request #9083
Opened 2024-05-01 17:39 UTC by dianabarsan

# Description

#9080

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2024-05-02 08:33 UTC, garethbowen requested changes
One refactor suggestion, but otherwise this is great!

2024-05-02 08:33 UTC, garethbowen commented on shared-libs/logger/src/index.js
> +} else {
Having different `module.exports` code depending on this branch makes it really hard to work out what it's going to do, especially if you're calling it from another shared lib and you don't know what context you're in. I think it'd be easier to read if it was something like...

```js
const create() => {
  if (!process || process.browser) {
    return console;
  } else {
    return require('./node-logger.js').create();
  }
};

module.exports = create();
module.exports.DATE_FORMAT = DATE_FORMAT;
```

2024-05-02 08:33 UTC, garethbowen commented on shared-libs/outbound/src/outbound.js
> +module.exports = {
:heart:

2024-05-02 08:33 UTC, garethbowen commented on shared-libs/transitions/test/unit/transitions/mark_for_outbound.js
> -const rewire = require('rewire');
Woohoo! Death to rewire!

2024-05-02 13:05 UTC, dianabarsan commented on shared-libs/transitions/test/unit/transitions/mark_for_outbound.js
> -const rewire = require('rewire');
yes! i concur!

2024-05-02 13:12 UTC, garethbowen commented
@dianabarsan One more random thought... in node services we often log like `log.error("got error: %o", err)` - but that won't work in the browser, right? Do we have to just be careful to not use that format in shared-libs?

2024-05-02 13:17 UTC, dianabarsan commented
> in node services we often log like log.error("got error: %o", err)

Correct, this kind of formatting won't work in the browser. Nothing is going to break, but we won't achieve the desired result. I suppose we can continue to use this format when we know the code will only be used in nodejs - in libraries like server-checks for example.

2024-05-02 14:02 UTC, garethbowen commented
@dianabarsan What about this: https://www.npmjs.com/package/winston-transport-browserconsole ? It might mean the logging API is consistent between node and browser?

2024-05-03 04:16 UTC, dianabarsan commented
> @dianabarsan What about this: https://www.npmjs.com/package/winston-transport-browserconsole ? It might mean the logging API is consistent between node and browser?

I've read about it. People said it bulks the browser bundle. I'll try it out though.

2024-05-04 03:39 UTC, dianabarsan commented
It looks like `winston-transport-browserconsole` it doesn't work out of the box:

![image](https://github.com/medic/cht-core/assets/35681649/65fbae1c-a798-44b1-af2a-690b79644d24)

It looks like `setImmediate` has been deprecated for a while: https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate and the library hasn't received any update in years. I'm reluctant to use it. 

Do you think it's worth more time working out how to generalize logging in webapp in this PR?

2024-05-06 06:50 UTC, garethbowen approved these changes
Awesome, thanks!

2024-05-06 12:34 UTC, merged