chore(#8181): remove old action bar
medic/cht-core pull request #9297
Opened 2024-08-02 10:37 UTC by latin-panda

# Description

**WIP**

#8181

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2024-08-02 10:46 UTC, latin-panda commented
@Benmuiruri @kapelo The heavy work is done, but I still need to test it more and clean it. 
I would appreciate your feedback at this stage, especially if there's unused code to remove (variables, functions, imports, etc).

2024-08-05 10:31 UTC, latin-panda commented on tests/e2e/default/contacts/fab-actions.wdio-spec.js
This was just a file renaming, and the action bar section was removed.
The test cases you see here are the original ones.

2024-08-05 10:57 UTC, latin-panda commented
@Benmuiruri @kapelo I finished cleaning the PR. It's ready for a review

2024-08-06 12:17 UTC, Benmuiruri requested changes
Looking good, great effort tracking down all those instances. 

I found 1 ghost 👻  function.

2024-08-06 12:17 UTC, Benmuiruri commented on webapp/src/ts/modules/reports/reports-more-menu.component.html
> +<section class="more-options-menu-container" *ngIf="(displayExportOption() || displayDeleteOption() || displayEditOption())">
```suggestion
<section
  class="more-options-menu-container"
  *ngIf="(displayExportOption() || displayDeleteOption() || displayEditOption())">
```

2024-08-06 14:51 UTC, latin-panda commented on webapp/src/ts/modules/contacts/contacts-more-menu.component.html
> +<section class="more-options-menu-container" *ngIf="(displayExportOption() || displayDeleteOption() || displayEditOption())">
Resolved!

2024-08-06 14:52 UTC, latin-panda commented on webapp/src/ts/modules/reports/reports-more-menu.component.html
> +<section class="more-options-menu-container" *ngIf="(displayExportOption() || displayDeleteOption() || displayEditOption())">
Resolved!

2024-08-07 07:10 UTC, Benmuiruri approved these changes
LGTM!

2024-08-09 06:22 UTC, kapelo approved these changes
LGTM

2024-08-09 06:23 UTC, merged