chore(#9327): add feature flag and hide old navigation
medic/cht-core pull request #9330
Opened 2024-08-14 12:09 UTC by Benmuiruri

# Description

This is the first deliverable of this issue to update the [Navigation](https://github.com/medic/care-teams/issues/24)

This PR completes this [task](https://github.com/medic/care-teams/issues/127)  to Add feature flag and hide old navigation
- Add new permission in default config with no roles: `can_view_old_navigation`
- Add a constant for this permission `header.component.ts` and exports it.
- hides the old navigation by default and only shows old navigation if user has permission. 

<details>
<summary>Desktop view</summary>

![Screenshot 2024-08-14 at 14 57 38](https://github.com/user-attachments/assets/8df65d2c-22d4-4e01-bb8f-ef57fb2b17ef)

</details>

<details>
<summary>Mobile View  with search</summary>

![Screenshot 2024-08-14 at 14 57 57](https://github.com/user-attachments/assets/ca4ad98f-b762-460a-8feb-d850aa6c597f)

</details>

<details>
<summary>Mobile view without search</summary>

![Screenshot 2024-08-14 at 14 58 12](https://github.com/user-attachments/assets/7d7a00bc-b33c-457e-9d01-50eeddb357e8)

</details>

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2024-08-15 13:03 UTC, latin-panda requested changes
Thanks for shipping! 
One small comment in the html but you will need to update the css too

2024-08-15 13:03 UTC, latin-panda commented on webapp/src/ts/app.component.html
> +  <div class="container-fluid" *ngIf="initialisationComplete" [class.old-nav]="!useOldNav">
The `old-nav` class is applied when the auth.has(`can_view_old_navigation`) is true.

```suggestion
  <div class="container-fluid" *ngIf="initialisationComplete" [class.old-nav]="useOldNav">
```

2024-08-20 10:01 UTC, latin-panda approved these changes
Looks good! ✨
Thanks @Benmuiruri , ready to go!

2024-08-20 12:03 UTC, kapelo approved these changes
LGTM!

2024-08-22 16:27 UTC, merged