dnm - CouchDB Nouveau
medic/cht-core pull request #9541
Opened 2024-10-14 17:15 UTC by m5r

# Description

- `npm run local-images`
- `COUCHDB_USER=admin COUCHDB_PASSWORD=pass docker compose -f ./local-build/cht-couchdb.yml -f ./local-build/cht-couchdb-override.yml up -d`

Put this into `./local-build/cht-couchdb-override.yml`: 
```yaml
services:
  couchdb:
    ports:
      - "5984:5984"
      - "5986:5986"

  nouveau:
    ports:
      - "5987:5987"
      - "5989:5989"
```

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2025-03-31 09:36 UTC, sugat009 commented
@jkuester I wanted to confirm if the starts-with searching was changed.

I created a contact named `contact1` whose id is `1ac9597f-6835-43e2-8a40-e05e1109454f`

![image](https://github.com/user-attachments/assets/95de84d9-8665-45b4-be70-fcbd5d055fcb)

When I query the view for `q="\"contact\""`, I only get the other contact whose fields(name, in this case, are `contact`).

![image](https://github.com/user-attachments/assets/2a750af0-c8e3-4d73-86a4-bff24bd5d6d4)

2025-03-31 18:03 UTC, jkuester commented on webapp/src/ts/services/search.service.ts
> +  search(type, filters: Filter, options:SearchOptions = {}) {
FYI, I had to make all the changes around the signature of this function because Sonar was complaining.  I resisted the urge to do a broader refactor of this code (it could use it). However, I think combining the params and adding types actually did help improve the readability of this code... :+1:

2025-03-31 18:09 UTC, jkuester commented
@sugat009 is is now ready to review!  The k3s tests are still failing as expected, but everything else should work and be ready for a proper review! :+1:

2025-04-03 08:08 UTC, sugat009 requested changes
@jkuester Nice! Some nitpicks, nothing major.

2025-04-07 17:18 UTC, jkuester commented on couchdb-nouveau/Dockerfile
> +FROM couchdb:3.4.2-nouveau
Good question!  My intention was to get us stable on `3.4.2` so that we can test a full upgrade to `3.4.3` in isolation in a separate sub-task.  

I logged https://github.com/medic/cht-core/issues/9882 to track this!

2025-04-07 22:04 UTC, merged