feat(#8034): replicate primary contacts at max depth
medic/cht-core pull request #9593
Opened 2024-10-30 12:54 UTC by dianabarsan

# Description

Adds configuration that allows replication of primary contacts and their associated reports and target documents at max depth. 
At the moment, it enforces that the primary contact be a child of a place that is allowed for the user to see, which is not a generally enforced rule for primary contacts. 

#8034

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2025-02-17 15:09 UTC, dianabarsan commented
Hi @jkuester 
I'd love a set of eyes on this before I send it out to be user tested. Appreciate your time!

2025-02-18 21:50 UTC, kennsippell commented
Did a very quick test on eCHIS KE config via https://github.com/moh-kenya/config-echis-2.0/pull/2564. This appears to allow CHA supervisors to monitor CHP performance.

2025-02-19 23:13 UTC, jkuester requested changes
Disclaimer: all my comments here should be taken as _highly speculative_!  If the question/comment does not make sense, don't spend a lot of time trying to understand it. :sweat_smile: I am probably just confused.  I think I followed _most_ of what is going on here, but that auth service code is insane!  (RIP to my brain.... :skull: )

2025-02-19 23:13 UTC, jkuester commented on api/src/services/authorization.js
> -const alwaysAllowCreate = doc => {
question: This was no longer needed because `feedback` docs are stored in `medic-users-meta` correct?  Are we concerned about an upgrade scenario where clients have existing `feedback` docs offline in their `medic` db (from pre-upgrade) and now, post-upgrade, these docs will not sync?

2025-02-19 23:13 UTC, jkuester commented on tests/integration/api/controllers/replication.spec.js
> +  expect(receivedIds.sort()).to.have.members([ ...expectedIds, ...DEFAULT_EXPECTED ].sort());
nitpick: Do we need the `sort()` calls here?  I learned recently that `to.have.members` does a strict unordered contains assertion!  😅

2025-02-20 10:44 UTC, dianabarsan commented on api/src/services/authorization.js
> + * @typedef {{
I know, right?! :)) 
The IDE does a good job to mediate though.

2025-02-20 10:45 UTC, dianabarsan commented on api/src/services/authorization.js
> +  return authorizationContext.subjectIds.includes(docId) || authorizationContext.subjectIds.includes(shortcode);
In this particular case, no, because what we expect are uuids in the `contact` property of the place.

2025-02-20 10:47 UTC, dianabarsan commented on api/src/services/authorization.js
> +    const result = await db.medic.allDocs({ keys: unknownPrimaryContacts, include_docs: true });
Ok, you're right. I think I can use a different view here.

2025-02-20 10:49 UTC, dianabarsan commented on api/src/services/authorization.js
> +  } while (newSubjects && authorizationCtx.replicatePrimaryContacts);
I thought a lot about preserving view results somehow. It just ended up with some complicated additional data structures which I thought were just ending up as overwhelming otherwise non-complex code. 
I ended up dumping that and trying to keep things as simple as possible, but I _still_ needed the contacts list. I suppose I can now just store view results in this structure.

2025-02-20 10:50 UTC, dianabarsan commented on api/tests/mocha/services/authorization.spec.js
> -const should = require('chai').should();
I think static analysis was complaining. Otherwise I would not have removed it. I don't recall this at all.

2025-02-20 10:51 UTC, dianabarsan commented on tests/integration/api/controllers/replication.spec.js
> +  expect(receivedIds.sort()).to.have.members([ ...expectedIds, ...DEFAULT_EXPECTED ].sort());
OMG this is for when your test fails and you get the differences in the log. If they are sorted, then it's super easily visible what the differences are, otherwise you have a +- mash of which element is in one array and which one in the other.

2025-02-20 11:44 UTC, dianabarsan commented on ddocs/medic-db/medic/views/places_by_primary_contact/map.js
> +  var types = [ 'district_hospital', 'health_center', 'clinic', 'person' ];
Wow, thanks for seeing this. I'm sure I copied this from somewhere, and we might have an issue there too!

2025-02-20 11:50 UTC, dianabarsan commented on api/src/services/authorization.js
> -const alwaysAllowCreate = doc => {
We moved feedback docs from medic to users-meta back in `3.5.0` (https://github.com/medic/cht-core/issues/4898) . I am not concerned about projects upgrading from 3.5.0 anymore.

2025-02-20 13:48 UTC, jkuester commented on api/src/services/authorization.js
> +  } while (newSubjects && authorizationCtx.replicatePrimaryContacts);
To be clear, I am fine prioritizing simple more maintainable code if you think there is not a big performance concern here!  I _think_ this code is not part of the main replication flow, but is more for edge-case asset syncing. So, maybe we do not have to be so worried about duplicating the view queries...

2025-02-20 13:50 UTC, jkuester commented on api/src/services/authorization.js
> -const alwaysAllowCreate = doc => {
:+1:  Perfect!

2025-02-20 13:51 UTC, jkuester commented on tests/integration/api/controllers/replication.spec.js
> +  expect(receivedIds.sort()).to.have.members([ ...expectedIds, ...DEFAULT_EXPECTED ].sort());
:sweat_smile:   Ahh, got it!

2025-02-21 07:11 UTC, dianabarsan commented on api/src/services/authorization.js
> +  } while (newSubjects && authorizationCtx.replicatePrimaryContacts);
Indeed, this is an edge case for syncing now. it used to be part of primary replication code, but now it's a fallback for when the `_bulk_get` request fails. This _can_ be called sometimes, but I would consider it a rare occasion now.
I wouldn't expect the iterations to ever go over a large number of docs here: it's always what's in the hierarchy of a certain contact, so we have low number of docs (definitely under 50, assuming crazy hierarchy and primary contacts). The view map is a tiny Javascript function. I'm not worried this is a performance hit.

2025-02-21 19:46 UTC, jkuester approved these changes
LGTM!  Super stoked to get this functionality added!

2025-02-24 06:15 UTC, dianabarsan commented
@kennsippell 
I would appreciate another round of testing before I merge this. 
Thanks!

2025-03-03 09:01 UTC, kennsippell commented
I'll make time for some more testing this week and report back.

2025-03-08 13:19 UTC, kennsippell commented
Tested with eCHIS Kenya config and I can see targets when `replicate_primary_contacts: true` and I can't see them when it is false. 

Regression tested a needs_signoff replication. Did some exploratory testing for users with multiple roles. Didn't do any perf. Didn't test scenarios where the PC is not within the place.

I noticed:

1. Create role A is `{ depth: 1, replicate_primary_contacts: true }`
1. Create role B is `{ depth: 1, replicate_primary_contacts: false }`
2. Create user `good` with roles `[A, B]` and I see the primary contacts
3. Create user `bad` with roles `[B, A]` and I dont see the primary contacts

2025-03-11 15:42 UTC, kennsippell commented
So options for disambiguating roles with equal depth are something like:

1. Take permission of the role listed first (today)
2. Merge permissions from roles (eg. take most permissive setting from all at same depth)
3. Take permissions of one role deterministically (eg. first role listed in app_settings)

I find option 1 to be the most confusing. Maybe this is obvious, but the order roles are specified isn't visible without going into database.

I would never expect that _adding a role_ is expected to restrict a user. With that in mind, I'd probably lean toward taking the most permissive permission from all roles at the highest depth. 

> I believe that would be thoroughly confusing to follow and selecting all values from one role is the easiest to understand).

Seems quite reasonable. I don't know the answer. If you believe this, I think option 3 is much better than option 1. Would be an improvement from how things are today.

2025-03-11 16:16 UTC, dianabarsan commented
Thanks for your input, @kennsippell . 
I think you're correct that #3 is the easiest to document and would reduce confusion significantly. I'll make the change.

2025-03-11 19:27 UTC, dianabarsan commented
Upon further consideration, I went with option 2. Mainly because we have a precedent of this behavior when we check for permissions, always favoring the permission from the role that grants it. 
So now, for the highest contact replication depth, we would select the most permissive report_depth and replicate_primary_contacts - not necessarily for the same role setting.

2025-03-13 15:25 UTC, dianabarsan commented
@jkuester I pushed one small change at @kennsippell 's request. would you be so kind to check this and share your thoughts? I'll wait for approval for either of you to merge this. 
Appreciate your time!

2025-03-13 19:20 UTC, jkuester approved these changes
Send it!  :rocket:

2025-03-13 19:31 UTC, merged